"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useState } from "react";
import { useResource, money, renewalDays, type AccountSummary } from "@/lib/workspace";
import { WorkspaceStatus } from "@/components/workspace-status";
export default function AccountsPage() {
  const query=useSearchParams().get("q")??"";
  const [sort,setSort]=useState("priority"),[level,setLevel]=useState("All");
  const resource=useResource<{items:AccountSummary[]}>(`accounts?sort=${sort}&search=${encodeURIComponent(query)}`);
  if(!resource.data)return <WorkspaceStatus {...resource}/>;
  const items=resource.data.items.filter(a=>level==="All"||a.priority.level===level);
  return <div className="flex flex-col gap-md"><p className="text-body-sm text-on-surface-muted">Synthetic KasirNusa data. Global ranking follows the selected sort; focus accounts are labelled separately.</p><section className="card"><div className="flex flex-wrap items-end gap-sm"><h2 className="card-title mr-auto">{items.length} accounts</h2><label className="text-label-sm">Level<select className="input ml-sm" value={level} onChange={e=>setLevel(e.target.value)}>{["All",...new Set(resource.data.items.map(a=>a.priority.level).filter((v):v is string=>!!v))].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-label-sm">Sort<select className="input ml-sm" value={sort} onChange={e=>setSort(e.target.value)}><option value="priority">Priority</option><option value="weighted">Weighted value</option><option value="renewal">Renewal date</option></select></label></div><div className="mt-md overflow-x-auto"><table className="w-full text-left text-body-sm"><thead className="label-caps text-on-surface-muted"><tr>{["Account","Priority","Coverage","Renewal","Annual value","Weighted value"].map(x=><th key={x} className={`whitespace-nowrap p-sm ${["Priority","Coverage","Annual value","Weighted value"].includes(x)?"text-right":""}`}>{x}</th>)}</tr></thead><tbody>{items.map(a=><tr key={a.id} className="border-t border-outline"><th className="min-w-48 p-sm font-normal"><Link className="inline-flex min-h-11 items-center font-semibold hover:text-primary" href={`/accounts/${a.id}`}>{a.name}</Link><p className="text-label-sm text-on-surface-muted">{a.id}{/^C0[1-6]$/.test(a.id)&&" · Focus"}</p></th><td className="whitespace-nowrap p-sm text-right">{a.priority.level??"Unscored"} · {a.priority.score??"—"}</td><td className="p-sm text-right">{a.priority.coverage??"—"}%</td><td className="whitespace-nowrap p-sm">{a.renewalDate??"Unavailable"}<p className="text-label-sm text-on-surface-muted">{renewalDays(a)??"—"} days from snapshot</p></td><td className="whitespace-nowrap p-sm text-right">{money(a.annualValueIdr)}</td><td className="whitespace-nowrap p-sm text-right">{money(a.weightedValueIdr)}</td></tr>)}</tbody></table></div>{!items.length&&<p className="mt-md text-body-sm text-on-surface-muted">No accounts match. Clear the search or level filter.</p>}</section><WorkspaceStatus {...resource}/></div>;
}
