"use client";
import Link from "next/link";
import { Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { api } from "@/lib/workspace";
import { ShapeGrid } from "@/components/ui/shape-grid";
function LoginForm(){const query=useSearchParams();const[error,setError]=useState(""),[busy,setBusy]=useState(false);return <section className="card w-full max-w-[28rem]"><span className="mb-md flex items-center gap-sm card-title"><span className="grid size-9 place-items-center rounded-sm bg-primary text-on-primary"><svg viewBox="56 56 144 144" className="size-4" aria-hidden><path fill="currentColor" d="M56 56H200V104H152V200L104 152V104Z"/></svg></span>Tessera</span><h1 className="text-headline-md font-semibold">Sign in to Tessera</h1><p className="mt-sm text-body-sm text-on-surface-muted">Use the demo credentials provided by your workspace administrator. KasirNusa data is synthetic.</p><form method="post" className="mt-lg flex flex-col gap-md" onSubmit={async e=>{e.preventDefault();const password=String(new FormData(e.currentTarget).get("password"));setBusy(true);setError("");try{await api("auth/login","POST",{password});const next=query.get("next");window.location.assign(next?.startsWith("/")&&!next.startsWith("//")&&!next.includes("\\")?next:"/dashboard");}catch(cause){setError(cause instanceof Error?cause.message:"Sign in failed.");setBusy(false);}}}><label className="text-label-md">Password<input name="password" type="password" autoComplete="current-password" required maxLength={256} className="input mt-xs w-full"/></label>{error&&<p className="text-body-sm text-danger" role="alert">{error}</p>}<button className="btn btn-primary" disabled={busy}>{busy?"Signing in…":"Enter workspace"}</button><p className="text-body-sm text-on-surface-muted">Demo password: <span className="font-mono text-on-surface">admin1234567</span></p></form></section>}
export default function LoginPage(){return <div className="relative grid min-h-dvh place-items-center p-md"><ShapeGrid/><Link href="/" className="btn btn-secondary absolute top-md left-md"><ArrowLeft size={16} aria-hidden/>Back</Link><div className="relative w-full max-w-[28rem]"><Suspense fallback={<p role="status">Loading sign in…</p>}><LoginForm/></Suspense></div></div>}
