"use client";
import { useSearchParams } from "next/navigation";
import { useState } from "react";
import Link from "next/link";
import { api,useResource,type Action } from "@/lib/workspace";
import { WorkspaceStatus } from "@/components/workspace-status";
function ActionForm({action,decisionId,onSaved}:{action?:Action;decisionId?:string;onSaved:()=>void}){const[busy,setBusy]=useState(false),[error,setError]=useState("");return <form method="post" className="flex flex-col gap-sm" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError("");try{await api(action?`actions/${action.id}`:"actions",action?"PATCH":"POST",{decisionId,expectedRevision:action?.revision,owner:f.get("owner"),dueDate:f.get("dueDate"),status:f.get("status"),note:f.get("note"),outcome:f.get("outcome")});onSaved();}catch(c){setError(c instanceof Error?c.message:"Action save failed.");}finally{setBusy(false);}}}><div className="grid gap-sm md:grid-cols-3"><label className="text-label-sm">Owner<input name="owner" required maxLength={120} className="input mt-xs w-full" defaultValue={action?.owner}/></label><label className="text-label-sm">Due date<input name="dueDate" type="date" required className="input mt-xs w-full" defaultValue={action?.dueDate}/></label><label className="text-label-sm">Status<select name="status" className="input mt-xs w-full" defaultValue={action?.status??"planned"}>{["planned","in_progress","blocked","completed","cancelled"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label></div><label className="text-label-sm">Progress and reason<textarea name="note" required maxLength={4000} className="input mt-xs min-h-20 w-full" defaultValue={action?.note}/></label><label className="text-label-sm">Observed result (required when completed)<textarea name="outcome" maxLength={4000} className="input mt-xs min-h-20 w-full" defaultValue={action?.outcome??""}/></label>{error&&<p role="alert" className="text-body-sm text-danger">{error}</p>}<button className="btn btn-primary self-start" disabled={busy}>{busy?"Saving…":action?"Record progress":"Start tracking"}</button></form>}
function History({id}:{id:string}){const r=useResource<{items:{id:string;revision:number;actorId:string;status:string;note:string;outcome:string|null;createdAt:string}[]}>(`actions/${id}/history`);return <div className="mt-md"><WorkspaceStatus {...r}/>{r.data?.items.map(e=><div key={e.id} className="mt-sm border-t border-outline pt-sm text-body-sm"><p>Revision {e.revision} · {e.status} · {e.actorId} · {e.createdAt}</p><p className="mt-xs">{e.note}</p>{e.outcome&&<p className="mt-xs">Observed result: {e.outcome}</p>}</div>)}</div>}
export default function ActionsPage(){const r=useResource<{items:Action[]}>("actions"),decision=useSearchParams().get("decision"),[created,setCreated]=useState(false),[history,setHistory]=useState<string|null>(null);return <div className="flex flex-col gap-md"><p className="text-body-sm text-on-surface-muted">Track execution after human approval. Progress is append-only and does not change priority scores.</p><WorkspaceStatus {...r}/>{decision&&!created&&!r.data?.items.some(a=>a.decisionId===decision)&&<section className="card"><h2 className="card-title">Track approved plan</h2><div className="mt-md"><ActionForm decisionId={decision} onSaved={()=>{setCreated(true);r.refresh();}}/></div></section>}{r.data?.items.map(a=><section key={`${a.id}-${a.revision}`} className="card"><div className="flex flex-wrap gap-sm"><h2 className="card-title mr-auto"><Link href={`/accounts/${a.accountId}`} className="hover:text-primary">{a.accountName}</Link></h2><span className={`badge ${a.stuck?"text-warning":"text-on-surface-muted"}`}>{a.stuck?"Needs progress · ":""}{a.status.replaceAll("_"," ")}</span></div><p className="mt-sm text-body-sm">{a.plan}</p>{a.stuck&&<p className="mt-sm text-body-sm text-warning">Suggested next step: ask {a.owner} to review the blocker or overdue commitment, record an updated next step and agree on a realistic due date. Basis: status {a.status}, due {a.dueDate}, progress “{a.note}”.</p>}<div className="mt-md">{["completed","cancelled"].includes(a.status)?<><p className="text-body-sm">{a.owner} · {a.dueDate} · {a.note}</p><p className="mt-sm text-body-sm">Observed result: {a.outcome??"No outcome recorded; effectiveness unknown."}</p></>:<ActionForm action={a} onSaved={r.refresh}/>}</div><button className="btn btn-secondary mt-md" aria-expanded={history===a.id} onClick={()=>setHistory(history===a.id?null:a.id)}>Decision and progress history</button>{history===a.id&&<History id={a.id}/>}</section>)}{r.data&&!r.data.items.length&&!decision&&<section className="card"><h2 className="card-title">No actions recorded</h2><p className="mt-sm text-body-sm text-on-surface-muted">Approve a save plan, then choose Track execution to assign its owner and due date.</p><Link className="btn btn-secondary mt-md" href="/review">Open Review</Link></section>}</div>}
